name: readme-scribe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - 'main'

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: muesli/readme-scribe@master
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_README_UPDATER }}
      -
        uses: stefanzweifel/git-auto-commit-action@b0f4d47f590e46dfe55fea81b3b068cb0aab8678
        with:
          commit_message: 'Update generated README'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}