name: Update Readme.MD
version: 1.0.0

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - main
jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: muesli/readme-scribe@master
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_README_UPDATER }}
            with:
              template: "templates/README.md.tpl"
              writeTo: "README.md"
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Update README.md"
            branch: main
            commit_user_name: [🤖] read-me-scribe

